### ISSUE TITLE
No Image available in drone.image in AR.Drone 2.0

### ISSUE THREAD

**Issue by zeeshansayyed** [braincorp/python-ardrone#11]
The image property of the drone object is not being reported. When I printed the size of  it (since, it's supposed to be in string form) I get a 0. Also, there is no image displayed  in demo.py.

**Comment by jbpassot** [comment]
@shahensha, thanks for your comment. Unfortunately, I will not have time to fix this in a near future, please feel free to fix the issue and update the repo if you know how to do it. Thanks.

**Comment by jjh42** [comment]
Are you using an ARDrone 2 - I'm not sure if this still works with an ARDrone 1?

What happens if you directly run libardrone.py  (requires opencv).

Also, what do you mean the image is in string form. `ARDrone.get_image` should always return a numpy array (but if no image has been received then this will be all zeros). Maybe set a breakpoint on `ARdrone.set_image` and see what's going setting this to something else.

**Comment by zeeshansayyed** [comment]
Thanks a lot for the reply @jjh42,

I am using ARDrone 2

When I run libardrone.py, I get the following message in the beginning.
"Please install psyco for better video decoding performance.
Unable to bind video decoding methods with psyco. Proceeding anyways, but video decoding will be slow!"

When I print drone.image, I don't get anything.

When I print drone.image.size(), I get the following error.
AttributeError: 'str' object has no attribute 'size'

When I print size(drone.image), I get a 0

I have opencv installed.

Also, what is ARdrone.set_image or get_image. I don't see that in the code.

**Comment by jjh42** [comment]
@shahensha are you sure that you are using the master branch from this copy of python-ardrone and not some other fork's copy?

`libardrone.py` should contain [`set_image` and `get_image`](https://github.com/braincorp/python-ardrone/blob/master/libardrone/libardrone.py#L280) and, if I recall correclty, no longer require pysco.

**Comment by zeeshansayyed** [comment]
It appears that I was using some other forked repository. I don't know how that happened. I am sorry for the trouble.

Just one question, is it possible for me to get my hands on the raw image/video data? I wish to perform decoding in C and not in python.

**Comment by jjh42** [comment]
Sure. You just need to write your own version of the h264 decoder.

https://github.com/braincorp/python-ardrone/blob/master/libardrone/h264decoder.py

write is called is to pass in data (with parrot's special wrappers removed). Currently is just passes the info to ffmpeg

**Comment by zeeshansayyed** [comment]
When I use the master repository and call get_image, I get the same initial image again and again. In other words, when I run libardrone.py, What I see on the Video Window is just the first image which the drone takes. When I wrote another program which captures images at different time intervals, I got the same initial image. This is the image which the drone captures the moment it starts. To check how many times, the image_ready function (which in turn calls the set_image function) is called in ar2video, I added a print statement and observed that it is only called twice.

What is the decoding rate expected to be?

**Comment by jjh42** [comment]
This looks like you are not receiving the drone images, or perhaps you do
not have ffmpeg installed?

Sorry its hard to tell.

**Comment by zeeshansayyed** [comment]
I think I have ffmpeg installed. I will still try and test it by running a toy program which decodes a simple video using ffmpeg. Moreover, I am surprised because I get the first image.

**Comment by zeeshansayyed** [comment]
The problem was solved using avconv instead of ffmpeg.
